# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: 'about'
    weight: 20
  - name: Abstracts & Registration
    identifier: absmenu
    weight: 30
  - name: Important Dates
    parent: absmenu
    url: '#dates'
    weight: 10
  - name: Abstracts
    parent: absmenu
    url: 'abstract-guidelines'
    weight: 20
  - name: Registration
    parent: absmenu
    url: 'registration'
    weight: 30
  - name: Programme
    url: '#programme'
    weight: 40
  - name: Location & Accommodation
    url: 'location-accommodation'
    weight: 50
  - name: Organisers
    url: '#people'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
