# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: 'about'
    weight: 20
  - name: Important Dates
    url: '#dates'
    weight: 30
  - name: Programme
    url: '#programme'
    weight: 40
  - name: Location & Accommodation
    identifier: location-accommodation
    weight: 50
  - name: About Brisbane
    parent: location-accommodation
    url: 'location-accommodation/about-Brisbane'
    weight: 10
  - name: Accommodation
    parent: location-accommodation
    url: 'location-accommodation/accommodation'
    weight: 20
  - name: Organisers
    url: '#people'
    weight: 60
  - name: QTDU2023
    url: 'archive/QTDU2023'
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 80
